blog/urls.py
# encoding: utf-8
from django.conf.urls import patterns, url

# URLconf的本质是URL以及视图函数的映射表
# 当patterns只包含''的时候，'127.0.0.1:8000'自动显示congrate.不然就进行匹配
urlpatterns = patterns('blog.views',
    # url(r'^$', 'home', name='home'),
    url(r'^posts/$', 'all_posts', name='all_posts'),
    url(r'^(?P<blog_id>\d+)/(?P<link>[\w,-]*)/$', 'article', name='article'),
    # url(r'^write-new-post/$', 'add_article', name='add_article'),
    url(r'^create-new-post/$', 'create_article', name='create_article'),
)

mysite/apps/blog/urls.py
# encoding: utf-8
from django.conf.urls import patterns, url

# URLconf的本质是URL以及视图函数的映射表
# 当patterns只包含''的时候，'127.0.0.1:8000'自动显示congrate.不然就进行匹配
urlpatterns = patterns('mysite.apps.blog.views',
    url(r'^$', 'home', name='home'),
    url(r'^posts/$', 'all_posts', name='all_posts'),
    url(r'^about/$', 'about_me', name='about_me'),
    url(r'^(?P<blog_id>\d+)/(?P<link>[\w,-]*)/$', 'article', name='article'),
    # url(r'^write-new-post/$', 'add_article', name='add_article'),
    # url(r'^create-new-post/$', 'create_article', name='create_article'),  
)

mysite/urls.py
# encoding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # url(r'^', include('mysite.apps.home.urls')),
    # url(r'^account/', include('mysite.apps.account.urls')),
    url(r'^$', 'mysite.apps.blog.views.home'),
    url(r'^blog/', include('mysite.apps.blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),  
    # url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
)

mysite/apps/blog/models.py
# encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


# Create your models here.
"""
class User(models.Model):
    first_name = models.CharField(u'名', max_length=30)
    last_name = models.CharField(u'姓', max_length=40)
    # verbose_name: define the name shown in Django administration
    # also: ('e-mail', blank=True)
    email = models.EmailField('e-mail', blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)
"""

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', u"草稿"),
        ('p', u"发布"),
    )
    
    link = models.CharField(u'URL', max_length=50, default='') # is required
    title = models.CharField(u'标题', max_length=50, unique=True)
    author = models.ForeignKey(User, verbose_name=u'作者') # is required
    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    publish_time = models.DateTimeField(u'公开时间', null=True) # is required
    update_time = models.DateTimeField(u'修改时间', auto_now=True)
    abstract = models.CharField(u'摘要', max_length=200, default='', blank=True)
    content = models.TextField(u'内容', )
    status = models.CharField(u'状态', max_length=1, choices=STATUS_CHOICES, default=STATUS_CHOICES[1][0]) # is required
    is_public = models.BooleanField(u'公开', default=True)
    is_top = models.BooleanField(u'置顶', default=False)
    
    def save(self, *args, **kwargs):
        self.link = slugify(self.link)
        super(Post, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

"""
class Comment(models.Model):
    #authors = models.ManyToManyField(Author)
    author = models.CharField(max_length=30)
    email = models.EmailField('e-mail', blank=True)
    #publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()

    def __unicode__(self):
        return self.title
"""

mysite/apps/blog/forms.py
from .models import Post
from django.forms import ModelForm

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

blog/views.py
#!/usr/bin/activate
#encoding: utf-8

from django.shortcuts import render_to_response, get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required 
# from django.core.context_processors import csrf

from .models import Post
from .forms import PostForm

def _query_pages(request, pagination=False, **kwargs):
    blog_list = get_list_or_404(Post.objects.order_by('-publish_time'), **kwargs)
    if pagination:
        paginator = Paginator(blog_list, 10)
        page_num = request.GET.get('p', 1)
        try:
            contents = paginator.page(page_num)
        except PageNotAnInteger:
            page_num = 1
            contents = paginator.page(page_num)
        except EmptyPage:
            page_num = -1
            contents = paginator.page(paginator.num_pages)
        return contents, int(page_num)+1
    else:
        return blog_list


def home(request):
    # if request.user.is_authenticated():
    posts, page_num = _query_pages(request, pagination=True)
    return render_to_response('home.html', {'posts': posts, 'page_num': page_num})

# @login_required(login_url='/login/')
# def home(request):
#     return HttpResponse('Welcome, logout')

def all_posts(request):
    posts = _query_pages(request)
    return render_to_response('posts.html', {'posts': posts})

def article(request, blog_id, link=''):
    post = _query_pages(request, pk=blog_id)[0]
    return render_to_response('article.html', {'post': post})

def about_me(request):
    return render_to_response('about.html')

def page_not_found(request):
    return render_to_response('404.html')

# def login(request):
#     return render_to_response('login.html')

@csrf_exempt
@login_required(login_url='/login/')
def create_article(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid:
            form.save()  
        if 'title' in request.POST:
            q = request.POST.get('title')
            post = Post.objects.filter(title__icontains=q)
            return render_to_response('article.html', {'post': post})
            # return render_to_response(
            #     'article.html', 
            #     {'post': post},
            #     context_instance=RequestContext(request))
    return render_to_response('new.html')


    

mysite/apps/blog/views.py
#!/usr/bin/activate
#encoding: utf-8

from django.shortcuts import render_to_response, get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
# from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required 
# from django.core.context_processors import csrf

from .models import Post
from .forms import PostForm

def _query_pages(request, pagination=False, **kwargs):
    blog_list = get_list_or_404(Post.objects.order_by('-publish_time'), **kwargs)
    if pagination:
        paginator = Paginator(blog_list, 10)
        page_num = request.GET.get('p', 1)
        try:
            contents = paginator.page(page_num)
        except PageNotAnInteger:
            page_num = 1
            contents = paginator.page(page_num)
        except EmptyPage:
            page_num = -1
            contents = paginator.page(paginator.num_pages)
        return contents, int(page_num)+1
    else:
        return blog_list


def home(request):
    # if request.user.is_authenticated():
    posts, page_num = _query_pages(request, pagination=True)
    return render_to_response('blog/home.html', {'posts': posts, 'page_num': page_num})

# # @login_required(login_url='/login/')
# # def home(request):
# #     return HttpResponse('Welcome, logout')

def all_posts(request):
    posts = _query_pages(request)
    return render_to_response('blog/posts.html', {'posts': posts})

def article(request, blog_id, link=''):
    post = _query_pages(request, pk=blog_id)[0]
    return render_to_response('blog/article.html', {'post': post})

def about_me(request):
    return render_to_response('blog/about.html')

# def page_not_found(request):
#     return render_to_response('404.html')

# def login(request):
#     return render_to_response('login.html')

# @csrf_exempt
# @login_required(login_url='/login/')
# def create_article(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid:
#             form.save()  
#         if 'title' in request.POST:
#             q = request.POST.get('title')
#             post = Post.objects.filter(title__icontains=q)
#             return render_to_response('article.html', {'post': post})
#             # return render_to_response(
#             #     'article.html', 
#             #     {'post': post},
#             #     context_instance=RequestContext(request))
#     return render_to_response('new.html')


    

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">My Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:all_posts' %}">All Post</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:create_article' %}">Write New Post</a>
                    </li>
                    <li>
                        <a href="{% url 'about_me' %}">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% static 'img/cover.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {% block page_header %}{% endblock %}
                </div>
            </div>
        </div>
    </header>

    <!-- page Content -->
    {% block page_content %}{% endblock %}

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="http://weibo.com/u/1790037253">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/shirleyChou">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

blog/templates/home.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}

{% block page_header %}
<div class="site-heading">
    <h1>Home Page</h1>
        <hr class="small">
        <span class="subheading">*技术记录栈</span>
</div>
{% endblock %}

{% block page_content %}
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            {% for post in posts %}
                <div class="post-preview">
                    <a href="{% url 'blog:article' blog_id=post.id link=post.link %}">
                        <h2 class="post-title">
                           {{ post.title|safe }}
                        </h2>
                        <h3 class="post-subtitle">
                           {{ post.abstract|safe }}
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="{% url 'about_me' %}">{{ post.author.username}}</a> on {{ post.publish_time|date:"Y-m-d" }}.</p>
                </div>
                <hr>
             {% endfor %}

                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                    {% if page_num != 0 %}
                        <a href="/?p={{page_num}}">Older Posts &rarr;</a>
                    {% else %}
                        This Is The Last Page
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--<link href="bower_components/startbootstrap-clean-blog/css/bootstrap.min.css"></link>-->  


    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
    <!--<link href="bower_components/startbootstrap-clean-blog/css/clean-blog.min.css"></link>--> 

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">My Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:all_posts' %}">All Post</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:about_me' %}">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <!--{% static 'bower_components/startbootstrap-clean-blog/img/cover.jpg' %}-->
    <header class="intro-header" style="background-image: url('{% static 'img/cover.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {% block page_header %}{% endblock %}
                </div>
            </div>
        </div>
    </header>

    <!-- page Content -->
    {% block page_content %}{% endblock %}

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="http://weibo.com/u/1790037253">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/shirleyChou">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!--<script src="{% static 'bower_components/startbootstrap-clean-blog/js/jquery.js' %}"></script>-->   

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--<script src="{% static 'bower_components/startbootstrap-clean-blog/js/bootstrap.min.js' %}"></script>-->

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
    <!--<script src="{% static 'bower_components/startbootstrap-clean-blog/js/clean-blog.min.js' %}"></script>-->

</body>

</html>

mysite/templates/blog/home.html
{% extends "base/base.html" %}
{% block title %}Home Page{% endblock %}

{% block page_header %}
<div class="site-heading">
    <h1>Home Page</h1>
        <hr class="small">
        <span class="subheading">*技术记录栈</span>
</div>
{% endblock %}

{% block page_content %}
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            {% for post in posts %}
                <div class="post-preview">
                    <a href="{% url 'blog:article' blog_id=post.id link=post.link %}">
                        <h2 class="post-title">
                           {{ post.title|safe }}
                        </h2>
                        <h3 class="post-subtitle">
                           {{ post.abstract|safe }}
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="{% url 'blog:about_me' %}">{{ post.author.username}}</a> on {{ post.publish_time|date:"Y-m-d" }}.</p>
                </div>
                <hr>
             {% endfor %}

                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                    {% if page_num != 0 %}
                        <a href="/?p={{page_num}}">Older Posts &rarr;</a>
                    {% else %}
                        This Is The Last Page
                    {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/blog/new.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Write a new post</title>

    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">My Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:all_posts' %}">All Post</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:create_article' %}">Write New Post</a>
                    </li>
                    <li>
                        <a href="{% url 'about_me' %}">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% static 'img/cover.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Write A New Post</h1>
                        <hr class="small">
                        <span class="subheading">below</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

     <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">My Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:all_posts' %}">All Post</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:create_article' %}">Write New Post</a>
                    </li>
                    <li>
                        <a href="{% url 'about_me' %}">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <form method="post" action="" novalidate>
                    <!--{% csrf_token %}-->
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Title</label>
                            <input type="text" class="form-control" placeholder="Title" name="title" required data-validation-required-message="Please enter blog title.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>

<!--
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Author</label>
                            <input type="text" class="form-control" placeholder="Author" name="author" method="GET" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
-->

                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Abstract</label>
                            <textarea rows="4" class="form-control" placeholder="Abstract" name="abstract" required data-validation-required-message="Please enter blog abstract"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>

                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Content</label>
                            <textarea rows="8" class="form-control" placeholder="Content" name="content" required data-validation-required-message="Please enter blog content."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>

                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Link</label>
                            <input type="text" class="form-control" placeholder="Link" name="link" required data-validation-required-message="Please enter blog link.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>

                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>     
                        </div>
                    </div>
                <!--
                    <input type="text" name="title">
                    <input type="submit" value="Send">
                -->
                </form>
            </div>
        </div>
    </div>
    <hr>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="http://weibo.com/u/1790037253">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/shirleyChou">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2015</p>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>   